let memberData = [
    {   
        picture:"picture1",
        username:"name1",
        email:"email1",
        interest:"interest",
        field:"ml",
        position:"e",
        skill:"sleep",
        graduate:true,
    },
    {   
        picture:"picture2",
        username:"name2",
        email:"email2",
        interest:"interest2",
        field:"ml2",
        position:"e2",
        skill:"sleep2",
        graduate:false,
    },
    {   
        picture:"picture3",
        username:"name3",
        email:"email3",
        interest:"interest3",
        field:"ml3",
        position:"e3",
        skill:"sleep3",
        graduate:true,
    },     
    {   
        picture:"picture4",
        username:"name4",
        email:"email4",
        interest:"interest4",
        field:"ml4",
        position:"e4",
        skill:"sleep4",
        graduate:true,
    }
]
export {memberData}